path_mod           = "__better-train-system__/"
path_lib           = path_mod .. "lib/"
path_public_lib    = path_lib .. "public/"
path_compatibility = path_mod .. "compatibility/"
path_prototypes    = path_mod .. "prototypes/"
